---
title: "Organize NDVI"
author: "Anna Talucci"
date: "2025-04-24"
output: html_document
---

```{r clear environment, include=FALSE}
rm(list=ls())
```

# Overview

Combine spatial data in to single dataframe


color help
http://vrl.cs.brown.edu/color

# Packages

```{r}
library(tidyverse)
```

# Data

## ndvi


```{r}
ndvi_list <- list.files(path="../data/prefirendvi_mean_2025-05-01",pattern='*.csv', full.names = TRUE) 
```

```{r}
df_prefire <- map_dfr(ndvi_list, function(file) {
  read_csv(file) %>%
    mutate(source_file = tools::file_path_sans_ext(basename(file)))
})
```

```{r}
df_prefire
```




# Figures 

## Plot themes

```{r}
comp_theme = theme_bw() + theme(legend.position = "bottom") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"))
```


## ndvi
## Color coding
'#256676', Baltzer
'#7cd3eb', Bergeron
'#3a427d', Diaz Veraverbeke 
'#956bed', Dominque Arsonault - 
'#ffa8ff', Gundal/Nisson
'#8a2f6b', Hayes - 
'#f75ef0', Hung & Natali
'#1932bf', Kristen Reid
'#6e9df7', Lucas Brehaut 
'#45deb2', Metcalfe
'#069668', Pare
'#a5e841', Parisien - 
'#0b5313', Saperstein
'#cadba5' Walker

```{r}
( ndvi_plot = ggplot(df_prefire, aes(x=PI, y=NDVI, color = PI)) +
  geom_boxplot( linewidth = .3 ) + #,outlier.shape = NA, size = 3, shape = 21
  geom_jitter( size = 1, shape = 21) +
     scale_color_manual(values=c('#256676', '#7cd3eb', '#3a427d', '#ffa8ff', '#f75ef0', '#1932bf', '#6e9df7', '#45deb2', '#069668', '#0b5313', '#cadba5' ), name="") +
    stat_summary(fun=mean, geom="point", shape=23, size=2, color="tomato") +

  labs(x="Researcher", y="Prefire NDVI (mean growing season)") +
  coord_flip() +

  comp_theme +
    theme(legend.position = "none",
          axis.text.y = element_text(size=8),
          axis.text.x = element_text(size=8),
          strip.background = element_rect( color="white", fill="white", size=1.5, linetype="solid" )) +
    theme(strip.text.x = element_text(size = 9))
)
```

### Save Figures
```{r eval=FALSE, include=FALSE}
ggsave("../figures/boxplots/2025-05-01_prefireNDVImean.png", plot = ndvi_plot,  width = 6, height =5, units = c("in"), dpi=600, bg = "white" )
```

