---
title: "OrganizeDayOfBurnModisFireAtlas"
author: "Anna Talucci"
date: "2025-04-29"
output: html_document
---

```{r clear environment, include=FALSE}
rm(list=ls())
```

# Overview

Combine all point with DoB attribute for FWI extract.


# Packages

```{r}
library(sf)
library(tidyverse)
```

# Data
```{r}
fa2013 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2013_2025-04-28.shp", "fireAtlas_dob_2013_2025-04-28")
```

```{r}
fa2015 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2015_2025-04-28.shp", "fireAtlas_dob_2015_2025-04-28")
```

```{r}
fa2017 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2017_2025-04-28.shp", "fireAtlas_dob_2017_2025-04-28")
```

```{r}
fa2018 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2018_2025-04-28.shp", "fireAtlas_dob_2018_2025-04-28")
```

```{r}
fa2019 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2019_2025-04-28.shp", "fireAtlas_dob_2019_2025-04-28")
```

```{r}
fa2020 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2020_2025-04-28.shp", "fireAtlas_dob_2020_2025-04-28")
```

```{r}
fa2021 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2021_2025-04-28.shp", "fireAtlas_dob_2021_2025-04-28")
```

```{r}
fa2022 = st_read("../outputs/LCC_cleaned/points/dob/fireAtlas_dob_2022_2025-04-28.shp", "fireAtlas_dob_2022_2025-04-28")
```

## modis


```{r}
modislc = st_read("../outputs/LCC_cleaned/points/shapefiles/lc_pts_dob_allpts_2025-04-29.shp", "lc_pts_dob_allpts_2025-04-29")
```

```{r}
modislcc = st_read("../outputs/LCC_cleaned/points/shapefiles/lcc_pts_dob_allpts_2025-04-29.shp", "lcc_pts_dob_allpts_2025-04-29")
```

# Combine Dataframes

```{r}
modislc
( modislcc = modislcc %>% mutate(fireYr = as.numeric(fireYr)) )
```

```{r}
sort(unique(modislcc$fireYr))
```
```{r}
modis = bind_rows(modislc, modislcc)
```

```{r}
fa = bind_rows(fa2013, fa2015, fa2017, fa2018, fa2019, fa2020, fa2021, fa2022)
```

```{r}
modis
fa
```

```{r}
setdiff(fa$siteplot, modis$siteplot) 
```

```{r}
setdiff( modis$siteplot, fa$siteplot) 
```


```{r}
( modis_df = modis %>% st_drop_geometry() %>% select(row_id, PI, siteplot, dob))
```
```{r}
fa
```
```{r}
( fa_df = fa %>% st_drop_geometry() %>% mutate(ted_date = as.Date(paste(ted_year, ted_month, ted_day, sep = "-"))) %>% select(row_id, PI, siteplot, ted_doy, ted_date))
```

```{r}
modis_df %>% full_join(., fa_df, by=c("row_id", "siteplot"))
```




# Fill in dob

```{r}
( combined = modis %>% 
    full_join(., fa_df, by=c("row_id", "siteplot")) %>% 
    mutate(dob = coalesce(dob, ted_doy)) %>% 
    mutate(ted_date = as.character(ted_date)) %>% 
    mutate(date = coalesce(date, ted_date)) %>%
    dplyr::select(-PI.y) %>%
    rename(PI = PI.x)
)
```

```{r}
( filtered_df = combined %>%
  add_count(row_id) %>%
  filter(n== 1) )

unique(filtered_df$PI)
```

```{r}
( dob_df = combined %>% 
  group_by(siteplot) %>%
  slice(1) %>%
  ungroup() %>%
  drop_na(dob)
)
```
```{r}
sort(unique(dob_df$PI) )
```
"Dominique Arseneault" "Gundale/Nilsson"      "Hayes"                "Hung and Natali"     
[5] "Kirsten Reid"         "Metcalfe"             "Walker"  

Loosing "Baltzer", "Diaz-Veraverbeke", "Lucas Brehaut", "Pare", "Saperstein"
```{r}
dob_df %>% 
  group_by(PI, lat, lon, dob, date) %>% 
  summarise(n = n())
```

```{r}
cat(paste0(sprintf("'%s'", sort(unique(dob_df$date))), collapse = ", "))
```

```{r eval=FALSE, include=FALSE}
st_write(dob_df, "../outputs/LCC_cleaned/points/shapefiles/lc_lcc_dob_2025-04-29.shp", driver="ESRI Shapefile")
```