---
title: "organize FWI"
author: "Anna Talucci"
date: "2025-04-18"
output: html_document
---

```{r clear environment, include=FALSE}
rm(list=ls())
```

# Overview

Combine spatial data in to single dataframe


color help
http://vrl.cs.brown.edu/color


**PART OF WORK FLOW**

# Packages

```{r}
library(tidyverse)
```


# Data

## FWI

```{r}
( fwi_lc <- list.files(path="../data/2025-08-08_SpatialData/fwi_lc", pattern='*.csv', full.names = TRUE) %>% 
  map(~ read_csv(.x, col_types = cols(siteplot = col_character()))) %>% 
  bind_rows() %>%
  dplyr::select(-`system:index`, -.geo)
)

```

```{r}
( fwi_lcc <- list.files(path="../data/2025-08-08_SpatialData/fwi_lcc", pattern='*.csv', full.names = TRUE) %>% 
  map(~ read_csv(.x, col_types = cols(siteplot = col_character()))) %>% 
  bind_rows() %>%
  dplyr::select(-`system:index`, -.geo)
)

```

```{r}
names(fwi_lcc)
```

```{r}
fwi_lc
```

```{r}
write_csv(fwi_lc, "../outputs/LCC_cleaned/csv/2025-08-11_FWI_LC.csv")
write_csv(fwi_lcc, "../outputs/LCC_cleaned/csv/2025-08-11_FWI_LCC.csv")
```

